import UE from "./UE.js";

//ui/
import UE_ui_uiUtils from "./ui/uiutils.js";
// import UE_ui_UIBase from "./ui/uibase.js";
import UE_ui_Separator from "./ui/separator.js";
import UE_ui_Mask from "./ui/mask.js";
import UE_ui_Popup from "./ui/popup.js";
import UE_ui_ColorPicker from "./ui/colorpicker.js";
import UE_ui_TablePicker from "./ui/tablepicker.js";
// import UE_ui_Stateful from "./ui/stateful.js";
// import UE_ui_Button from "./ui/button.js";
import UE_ui_SplitButton from "./ui/splitbutton.js";
import UE_ui_ColorButton from "./ui/colorbutton.js";
import UE_ui_TableButton from "./ui/tablebutton.js";
import UE_ui_AutoTypeSetPicker from "./ui/autotypesetpicker.js";
import UE_ui_AutoTypeSetButton from "./ui/autotypesetbutton.js";
import UE_ui_CellAlignPicker from "./ui/cellalignpicker.js";
import UE_ui_PastePicker from "./ui/pastepicker.js";
import UE_ui_Toolbar from "./ui/toolbar.js";
import UE_ui_QuickOperate from "./ui/quick-operate.js";
import { UE_ui_Menu, UE_ui_MenuItem } from "./ui/menu.js";
import UE_ui_Combox from "./ui/combox.js";
import UE_ui_Dialog from "./ui/dialog.js";
import UE_ui_MenuButton from "./ui/menubutton.js";
import UE_ui_MultiMenuPop from "./ui/multiMenu.js";
import UE_ui_ShortCutMenu from "./ui/shortcutmenu.js";
import UE_ui_Breakline from "./ui/breakline.js";
import UE_ui_Message from "./ui/message.js";

import cls_uiButton from "./ui/button.cls.js";
import cls_uiStateful from "./ui/stateful.cls.js";
import cls_UIBase from "./ui/UIBase.cls.js";

//ui/
UE.ui.uiUtils = UE_ui_uiUtils;
UE.ui.UIBase = cls_UIBase;
UE.ui.Separator = UE_ui_Separator;
UE.ui.Mask = UE_ui_Mask;
UE.ui.Popup = UE_ui_Popup;
UE.ui.ColorPicker = UE_ui_ColorPicker;
UE.ui.TablePicker = UE_ui_TablePicker;
// UE.ui.Stateful = UE_ui_Stateful;
UE.ui.Stateful = cls_uiStateful;
// UE.ui.Button = UE_ui_Button;
UE.ui.Button = cls_uiButton;
UE.ui.SplitButton = UE_ui_SplitButton;
UE.ui.ColorButton = UE_ui_ColorButton;
UE.ui.TableButton = UE_ui_TableButton;
UE.ui.AutoTypeSetPicker = UE_ui_AutoTypeSetPicker;
UE.ui.AutoTypeSetButton = UE_ui_AutoTypeSetButton;
UE.ui.CellAlignPicker = UE_ui_CellAlignPicker;
UE.ui.PastePicker = UE_ui_PastePicker;
UE.ui.Toolbar = UE_ui_Toolbar;
UE.ui.QuickOperate = UE_ui_QuickOperate;
UE.ui.Menu = UE_ui_Menu;
UE.ui.MenuItem = UE_ui_MenuItem;
UE.ui.Combox = UE_ui_Combox;
UE.ui.Dialog = UE_ui_Dialog;
UE.ui.MenuButton = UE_ui_MenuButton;
UE.ui.MultiMenuPop = UE_ui_MultiMenuPop;
UE.ui.ShortCutMenu = UE_ui_ShortCutMenu;
UE.ui.Breakline = UE_ui_Breakline;
UE.ui.Message = UE_ui_Message;